# Generated by Django 4.1 on 2022-08-10 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catalogo', models.CharField(max_length=40)),
                ('especie', models.CharField(max_length=20)),
                ('genero', models.CharField(max_length=1)),
                ('dia_creacion', models.DateTimeField(default=datetime.datetime(2022, 8, 10, 2, 57, 13, 648569, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
